version: '3'
services:
  tests:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - '.:/app'

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - .env