version: '3'
services:
  tests:
    build:
      context: .
    volumes:
      - '.:/app'

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pylter
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pylter
    depends_on:
      - tests